
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 14 18:18:23 VET 2019
//----------------------------------------------------

package tiny;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 21;
  public static final int MOD = 28;
  public static final int READ = 8;
  public static final int OVER = 22;
  public static final int LT = 14;
  public static final int ELSE = 4;
  public static final int PLUS = 19;
  public static final int RPAREN = 24;
  public static final int THEN = 3;
  public static final int SEMI = 27;
  public static final int END = 5;
  public static final int IF = 2;
  public static final int LPAREN = 23;
  public static final int GT = 17;
  public static final int WRITE = 9;
  public static final int ID = 10;
  public static final int RCOR = 26;
  public static final int NUM = 11;
  public static final int LCOR = 25;
  public static final int LTEQ = 15;
  public static final int EOF = 0;
  public static final int MINUS = 20;
  public static final int error = 1;
  public static final int UNTIL = 7;
  public static final int ASSIGN = 12;
  public static final int EQ = 13;
  public static final int GTEQ = 18;
  public static final int DIFF = 16;
  public static final int REPEAT = 6;
}

