
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
<<<<<<< HEAD
// Sun Sep 15 17:38:18 VET 2019
=======
// Sun Sep 15 16:33:02 VET 2019
>>>>>>> for-instrucciones
//----------------------------------------------------

package tiny;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 21;
  public static final int OVER = 25;
  public static final int LTEQ = 18;
  public static final int TIPOENTERO = 35;
  public static final int EACH = 39;
  public static final int LPAREN = 26;
  public static final int SEMI = 30;
  public static final int REPEAT = 6;
  public static final int FOR = 37;
  public static final int MINUS = 23;
  public static final int RCOR = 29;
  public static final int WRITE = 11;
  public static final int RPAREN = 27;
  public static final int NOT = 34;
  public static final int AND = 32;
  public static final int LT = 17;
  public static final int OR = 33;
  public static final int BOOL = 14;
  public static final int UNTIL = 7;
  public static final int NUM = 13;
  public static final int PLUS = 22;
  public static final int ASSIGN = 15;
  public static final int IF = 2;
  public static final int ID = 12;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MOD = 31;
  public static final int EQ = 16;
  public static final int TIMES = 24;
  public static final int ELSE = 4;
  public static final int READ = 10;
  public static final int TO = 38;
  public static final int WHILE = 8;
  public static final int TIPOBOOL = 36;
  public static final int LCOR = 28;
  public static final int THEN = 3;
  public static final int END = 5;
  public static final int DIFF = 19;
  public static final int GT = 20;
  public static final int DO = 9;
}

