
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 16 12:13:09 VET 2019
//----------------------------------------------------

package tiny;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 20;
  public static final int OVER = 24;
  public static final int LTEQ = 17;
  public static final int TIPOENTERO = 34;
  public static final int EACH = 38;
  public static final int LPAREN = 25;
  public static final int SEMI = 29;
  public static final int REPEAT = 6;
  public static final int FOR = 36;
  public static final int MINUS = 22;
  public static final int RCOR = 28;
  public static final int WRITE = 11;
  public static final int RPAREN = 26;
  public static final int NOT = 33;
  public static final int AND = 31;
  public static final int LT = 16;
  public static final int OR = 32;
  public static final int UNTIL = 7;
  public static final int NUM = 13;
  public static final int PLUS = 21;
  public static final int ASSIGN = 14;
  public static final int IF = 2;
  public static final int ID = 12;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MOD = 30;
  public static final int EQ = 15;
  public static final int TIMES = 23;
  public static final int ELSE = 4;
  public static final int READ = 10;
  public static final int TO = 37;
  public static final int WHILE = 8;
  public static final int TIPOBOOL = 35;
  public static final int LCOR = 27;
  public static final int THEN = 3;
  public static final int END = 5;
  public static final int DIFF = 18;
  public static final int GT = 19;
  public static final int DO = 9;
}

